### ISSUE TITLE
Sensor battery fluctuations

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/msupply-cold-chain#246]
**Describe the bug**
Battery sensor suddenly dropped to 12%. On refreshing the screen it then changed to 48%. Breach alert for low battery also lighted up and on self-resolution of the battery sensor the breach alert stopped.

<img width="721" alt="image" src="https://github.com/openmsupply/msupply-cold-chain/assets/19318937/d76bc01e-ff4e-4c9a-a2b1-a149645e5552">

![IMAGE 2023-08-24 17:03:25](https://github.com/openmsupply/msupply-cold-chain/assets/143057869/0a9bcd0f-00dd-4a6b-a86b-5adc36392eac)

<img width="717" alt="image" src="https://github.com/openmsupply/msupply-cold-chain/assets/19318937/316a529c-d475-43ea-88e8-342d4e1007b1">

Pictures show battery % dropping dramatically very suddenly and then going back to prior battery %. Screenshots have been provided by client's Pharmacy Team.

**To Reproduce**
Unclear, however this is a common occurrence. https://docs.google.com/spreadsheets/d/1NpYpGs-mBIhhNx-4-oC1aylwXNn_0Q9tx4_EOJC9FjU/edit#gid=0

**Comment by adamdewey** [comment]
dev team - please consult with me before starting any work here

**Comment by adamdewey** [comment]
More reports of complaints about this coming in from the field. e.g. often jumping from 50 to 48 to 52, even down to 28.

Could we perhaps improve the accuracy by taking an average of, say, the last 20 battery readings (rounded to the nearest integer)

**Comment by jmbrunskill** [comment]
> More reports of complaints about this coming in from the field. e.g. often jumping from 50 to 48 to 52, even down to 28.
> 
> Could we perhaps improve the accuracy by taking an average of, say, the last 20 or 50 battery readings (rounded to the nearest integer)

I'm not sure if I just missed it, but it seems like we might not be recording historical battery readings, can't see it in my postgres at least? @Mai21 can you fill us in on that?

**Comment by adamdewey** [comment]
@jmbrunskill - correct, we're not currently. 

@Mai21 has done some magic to create a temporary table in postgres so we can see if it improves things, seems it would be a big improvement if we average the level over a 24 hour period: 

![image](https://github.com/openmsupply/msupply-cold-chain/assets/19318937/00c671a5-ef21-4ae5-87e9-6079efc1b010)

**Comment by mark-prins** [comment]
Perhaps revisit after #243 as we need historical data in order to average
Actual battery reading is from the sensor, and we have no control of the validity

**Comment by marthakeezy** [comment]
Moving to 'Not Ready to Test' as we are waiting for historical data as per Mark's comment above ^
