### ISSUE TITLE
Sensors are duplicated on server when sensor is unlinked and linked again in CCA

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/msupply-cold-chain#257]
**Describe the bug**
If a sensor is unlinked from CCA and then linked again (a common occurrence if the app has to be re-installed) then a duplicate sensor instance is created on the server: 

![image](https://github.com/openmsupply/msupply-cold-chain/assets/19318937/dc4175d6-cbcc-4012-a258-3b6ed5558eb5)

This causes issues for users down the line when doing something with the sensor - assigning a location, creating a notification etc as they don't know which is the true active sensor

<img width="1512" alt="image" src="https://github.com/openmsupply/msupply-cold-chain/assets/19318937/70c475eb-42bf-4c3d-bf55-a1c4c9521e6f">

**To Reproduce**
1. Assign a sensor in CCA
2. Sync to server
3. Unassign sensor in CCA
4. Reassign sensor in CCA
5. Sync to server

**Expected behavior**
System should be able to identify sensor as being previously linked to the Store (via mac / serial number) and re-use that sensor instance instead of creating a new one. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A8
 - OS: Android 13
 - Version 0.5.4

**Additional context**

**Comment by mark-prins** [comment]
Fixed with #274

**Comment by AnushaUp** [comment]
@adamdewey @mark-prins Tested on coldchain V0.5.6
I tested this by upgrading , installing and uninstalling coldchain and cannot recreate the issue.
But it seems like the sensors are duplicated when we downgrade the application in the lower version, hopefully the client won't do that😁

**Comment by adamdewey** [comment]
Nice one @AnushaUp - yeah I don't think we need to worry about them downgrading the app to lower than V0.5.6 :)
