### ISSUE TITLE
Show timestamps on Graphs

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/msupply-cold-chain#259]
**Is your feature request related to a problem? Please describe.**
It's difficult to tell what timerange is represented by the historical temperature graph.

**Describe the solution you'd like**
I think the system should always show say 24hours of data? Missing data recently would then show as a gap in the trend (or maybe a straight line), and if we don't have 24 hours of data it would be obvious.
With a hardcoded 24hr timeframe, we could get away with just something saying "Temperature Trend - Last 24hours"

- [ ] Increase datapoints to 48 to align with the 24 hour timeframe (1 datapoint every 30minutes)

**Describe alternatives you've considered**
- [ ] Make the time range configuable
- [ ] Use current approach averaging the data over 3 days for a 3day trend with 30 datapoints, unless we have less than 24hrs of data
- [ ] Show 3 days of data, but put the date/time somewhere in the graph UI
- [ ] Easy way to switch between common selections e.g. last hour, last 4hrs, last 24hrs?

**Additional context**

**Comment by AnushaUp** [comment]
This is what it looks like in the latest version of coldchain v0.5.6
![Screenshot_20240108_112454_mSupply ColdChain](https://github.com/msupply-foundation/msupply-cold-chain/assets/115983430/f0a94555-4392-4e0f-b24d-1ee171e70d2f)
