### ISSUE TITLE
Upgrade path for single url config

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/msupply-cold-chain#260]
**Describe the bug**
Issue #249 reduced the number of URLS needed to setup sync on the tablet, however, upgrades haven't be handled nicely.

**To Reproduce**
1. Upgrade to 0.5.3+ from old version 0.5.2 or earlier
2. Click on sync settings
3. Check that URL isn't configured corrrectly

**Expected behavior**
If the old configuration URL was set, but new one isn't, derived the settings from the login url

**Additional context**

**Comment by AnushaUp** [comment]
Tried upgrading from v0_5_0 to 0_5_6 and the path for single url config was correct. PASSED
