### ISSUE TITLE
Data capture stops when tablet screen is turned off or process goes to background?

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/msupply-cold-chain#263]
**Describe the bug**
The current cold chain app 0.5.5 has a WAKE_LOCK feature which is meant to keep cold chain app screen on.

Checked the tablet today - screen was off and when turning the screen on, it came up with this:

![photo_2023-11-10 16 08 51](https://github.com/msupply-foundation/msupply-cold-chain/assets/143057869/d948a157-3e43-4675-b750-fb831f549deb)

**To Reproduce**
dont know

**Expected behavior**
Screen is meant to be on always

**Smartphone (please complete the following information):**
cold chain app 0.5.5
tablet samsung 

**Additional context**
Checked MDM and screen timeout was set on 30 seconds. Have changed this to always be on - has not been long enough to confirm it will still keep on

**Comment by jmbrunskill** [comment]
Based on my reading of this doc, it sounds like wakelock might not work without also implementing background processing...
https://developer.android.com/training/scheduling/wakelock

As a short term fix, we should probably consider [FLAG_KEEP_SCREEN_ON](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_KEEP_SCREEN_ON) instead

**Comment by jmbrunskill** [comment]
Found my tablet at home like this too.

![telegram-cloud-photo-size-1-5073867277807496642-y](https://github.com/msupply-foundation/msupply-cold-chain/assets/8287373/c34dfcab-3144-48d5-aeaa-72154154f92e)

Seems like process can somehow go to background even with screen on?

**Comment by mark-prins** [comment]
I thought not to put in  FLAG_KEEP_SCREEN_ON because I was worried about battery usage, but given that the wakelock will drain the battery anyway, might as well

**Comment by mark-prins** [comment]
Fixed with #268

**Comment by AnushaUp** [comment]
Tested and passed👍
