### ISSUE TITLE
Ignore SSL errors for local server sync

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/msupply-cold-chain#264]
**Is your feature request related to a problem? Please describe.**
When synchronising with Open mSupply which is running on a tablet - the server is using a self-signed certificate and therefore the sync interaction from CCA fails due to the SSL cert error.

**Describe the solution you'd like**
For local addresses only, when synchronising, ignore SSL certificate errors.

**Comment by marthakeezy** [comment]
Mark confirmed the issue has been Dev build tested, so moving to Done ✅ :) Will keep an eye on general log synchronisation and reopen individual issues should any problems occur!
