### ISSUE TITLE
Configure server URL using QR code

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/msupply-cold-chain#266]
**Is your feature request related to a problem? Please describe.**
Open mSupply now sports a QR code with the server URL in it:

![telegram-cloud-photo-size-1-5104977667257642470-x](https://github.com/msupply-foundation/msupply-cold-chain/assets/9192912/daba46ad-e3d0-4a2d-93f8-e05c8ae7662a)

We would like to be able to scan this in CCA and have the server URL populated. like magic.

**Describe the solution you'd like**
A scan button next to the URL?
A scan button beside the input field?

Let's see what you can do.

**Describe alternatives you've considered**
It is possible to enter manually; using the QR might result in fewer errors however. and it's quicker. maybe.

**Comment by AnushaUp** [comment]
Tested and its working fine

https://github.com/msupply-foundation/msupply-cold-chain/assets/115983430/ea60cfbf-c5ba-440d-818b-5fccf18cadb6
