### ISSUE TITLE
Consistent ID for sensors when added

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/msupply-cold-chain#273]
**Is your feature request related to a problem? Please describe.**
When a sensor is added to the coldchain app, it's a assigned a random unique id.
If the app is re-installed and sensor added again, we get a new unique id creating duplicates in mSupply.

**Describe the solution you'd like**
An Id should be derived from the mac address on adding.

**Describe alternatives you've considered**
Just don't re-install? A good process for deleting old records from mSupply?

**Additional context**
Trello: https://trello.com/c/AMW6Tidc/31-bug-able-to-add-duplicate-sensors-to-system

**Comment by AnushaUp** [comment]
Tested and passed in `v0.5.6`
