### ISSUE TITLE
Internal documentation

### ISSUE THREAD

**Issue by josh-griffin** [msupply-foundation/msupply-cold-chain#28]
- We have a pretty good user guide
- We have no internal docs

We should have some internal docs!

**Comment by wlthomson** [comment]
Also suggest piggybacking updates to `README.md` with basic instructions for setting up environment and tasks like building, running tests etc.

**Comment by joshxg** [comment]
Have added a README(copy pasted from mobile).

Will try to work on some internal docs to put in the wiki

**Comment by marthakeezy** [comment]
Moving to Done as no testing needed :) ✅
