### ISSUE TITLE
Syncing lot of logs isn't reliable with poor internet connections

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/msupply-cold-chain#280]
**Describe the bug**
Currently syncing logs uses a Promise.all() request to try to send all the logs concurrently in batches of 20.

If there are a lot of logs, this results in a lot of connections to the server.
Additionally, we don't handle the failure of sending some logs well (the whole Promise.all() will exit I think)

**Expected behavior**

- [ ] Last sync shouldn't show as successful, if there were errors with timeouts of sending temperature logs
- [ ] The app should limit how many concurrent connections it creates.
- [ ] If there are a log of logs to send, the logs that have been sent should probably be marked as sent, without waiting for everything to be completed?

**Additional context**

**Comment by mark-prins** [comment]
yep, a promise.all() will reject when the first promise rejects.
perhaps don't send concurrently? and increase the batch size. what about batching the batches and run a handful concurrently?

**Comment by jmbrunskill** [comment]
> perhaps don't send concurrently? and increase the batch size. what about batching the batches and run a handful concurrently?

Yeah I'm thinking something similar...

**Comment by marthakeezy** [comment]
Mark confirmed the issue has been Dev build tested, so moving to Done ✅ :) Will keep an eye on general log synchronisation and reopen individual issues should any problems occur!
