### ISSUE TITLE
Simplify chart UI

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/msupply-cold-chain#282]
**Is your feature request related to a problem? Please describe.**
Might look nicer like this:

![2023-12-11 17 46 48](https://github.com/msupply-foundation/msupply-cold-chain/assets/9192912/af23b0b1-4fd4-4417-835e-88d4312e0e43)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Trello: https://trello.com/c/D6qysY5A/229-move-sensor-name-above-graphs

**Comment by AnushaUp** [comment]
Tested and Passed 👍
