### ISSUE TITLE
Can't see Login & Password fields in landscape mode for Sync Settings

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/msupply-cold-chain#286]
**Describe the bug**
When changing the Sync Settings (in landscape mode), the Login & Password fields are not visible and therefore cannot be modified. The OK button also is not clickable and the information can only be saved by pressing 'Done' on the keyboard. 

![Issue](https://github.com/msupply-foundation/msupply-cold-chain/assets/153777484/bb84dac2-6116-4347-8c1d-867301f19f4b)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings -> Sync
2. Click on 'Username' and then on the text field to enter the details
3. The same step can be repeated for the 'Password' field

**Expected behavior**
The fields appear centered on the screen and the 'OK' and 'Cancel' buttons are clickable. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A8
 - OS: Android 13
 - Version 0.5.6

**Additional context**

**Comment by marthakeezy** [comment]
Also, just noticed that when trying to change the interval of syncing under each individual sensor, the field exhibits the same behaviour. 

![image](https://github.com/msupply-foundation/msupply-cold-chain/assets/153777484/3356571d-5080-4f95-b956-22ee9d35e2a8)

**Comment by AnushaUp** [comment]
Thanks @marthakeezy for making this issue. It's really not comfortable for entering data 👍. Much needed

**Comment by jmbrunskill** [comment]
@mark-prins I fixed this locally by commenting out this in SettingsEditModalLayout.tsx
```
 const onKeyboardDidShow = useCallback(e => {
    // setKeyboardHeight(e.endCoordinates.height);
  }, []);
```

Not sure why this was added though, I'm guessing it was possibly needed somewhere else?

Do you think we should just remove this?

**Comment by marthakeezy** [comment]
Tested in `V0.5.7` - fixed :) Thanks team! ✅
