### ISSUE TITLE
Cannot remove the first digit when changing the Log Interval for each sensor

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/msupply-cold-chain#287]
**Describe the bug**

When trying to remove the first digit of a number, the text box does not allow you to do so. For example, if I want to change from 1 minute Log Interval to 5, the field does not allow me to remove 1 (e.g. the field does not allow it to be empty). 

![image](https://github.com/msupply-foundation/msupply-cold-chain/assets/153777484/7f3f2e85-e770-42b1-a893-e96b344117a7)

**To Reproduce**
1. Go to Settings -> Available Sensors -> click on a Sensor you want to change
2. Scroll down and click on Log Interval
3. Try and remove the first digit to enter a different number

**Expected behavior**

The first digit should be removed in order to enter a new number, however there can be an error presented to the user if they leave the field empty (or it can automatically set to the default number mentioned in settings, e.g. 5 minutes). 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A8
 - OS: Android Version 13
 - Version 0.5.6.

**Comment by mark-prins** [comment]
cf the issue in omSupply

**Comment by marthakeezy** [comment]
Tested in `V0.5.7` - fixed :) Thanks team! ✅
