### ISSUE TITLE
Temperature spike possible cause unravelled

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/msupply-cold-chain#317]
**Describe the bug**
Saw a spike on the 28th October on dashboard and tablet:

Dashboard:
<img width="1503" alt="Screenshot 2024-10-29 at 10 44 01 PM" src="https://github.com/user-attachments/assets/49d84ea9-0c5d-44dd-afd4-31357b148b3f">

Tablet logs for the spike sensor are:

<img width="804" alt="Screenshot 2024-10-29 at 10 54 36 PM" src="https://github.com/user-attachments/assets/ce14c3e2-973d-484d-8923-1e7e1560de05">

Sensor logs are:

<img width="532" alt="Screenshot 2024-10-29 at 11 19 18 PM" src="https://github.com/user-attachments/assets/cbd53eea-e4ad-434b-af40-151b7369ad7b">

What happened?
1) First lets just ignore the times it is a bit out of sync because I didn't set my date/time on tablet properly
2) We see on the sensor logs that cells highlighted in green have been picked up by CCA. Cells highlighted in orange have not, but instead potentially the humidity has been picked up as a temperature reading instead. 

Likely cause?
Data is mashed together and the wrong data got picked up and shown.

Now what?
Need a way to replicate this to find out where the bug lies in the code.

The suggestion from tech guy is:
1. Create a new special build with backdate option on the app and then re-pull the logs from the last 7 days for that particular sensor to see if it can be replicated.
2. If it can, this will be easier to fix
3. Make a build to have debug logs permanently turned on (there has been issues of it randomly turning off so have not been able to use these logs whenever there is a spike)

EDIT UPDATE:
Maybe worse than expected as noticed the other data points are not matching. Question raised if it is the way we are integrating logs...

![IMAGE 2024-10-29 23:36:54](https://github.com/user-attachments/assets/e4e94272-ce7e-494c-992c-ecdb0823c242)

![IMAGE 2024-10-29 23:37:00](https://github.com/user-attachments/assets/d6638330-34d5-47a9-a4c1-40ed781aae63)

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by louisaw123** [comment]
Adding more:

Blue maestro logs 1x 1.6 reading
<img width="661" alt="Screenshot 2024-10-30 at 9 14 52 AM" src="https://github.com/user-attachments/assets/9bf62ad8-946e-4846-9597-1cd8141ddd6b">

CCA app: 2x 1.6 reading
<img width="930" alt="Screenshot 2024-10-30 at 9 16 00 AM" src="https://github.com/user-attachments/assets/eb4c102e-4f59-4911-b729-005af2b55c61">

Export of CCA logs:
[C1671B0D_1730231726948_log.csv](https://github.com/user-attachments/files/17562647/C1671B0D_1730231726948_log.csv)


Debug logs for CCA for above:
[com.msupplycoldchain-2024-10-29.15.log](https://github.com/user-attachments/files/17562639/com.msupplycoldchain-2024-10-29.15.log)
[com.msupplycoldchain-2024-10-29.14.log](https://github.com/user-attachments/files/17562640/com.msupplycoldchain-2024-10-29.14.log)
[com.msupplycoldchain-latest (3).log](https://github.com/user-attachments/files/17562641/com.msupplycoldchain-latest.3.log)
[com.msupplycoldchain-2024-10-29.17.log](https://github.com/user-attachments/files/17562642/com.msupplycoldchain-2024-10-29.17.log)
[com.msupplycoldchain-2024-10-29.16.log](https://github.com/user-attachments/files/17562643/com.msupplycoldchain-2024-10-29.16.log)

**Comment by adamdewey** [comment]
Thanks for this @louisaw123 !

I'm suspecting there's possibly more than 1 issue going on here, so going to separate them into different GitHub issues. 

I've updated the original temperature spike issue with these findings. See https://github.com/msupply-foundation/msupply-cold-chain/issues/251

I'll raise a new issue to investigate the logs being skipped / duplicated (I suspect this is responsible for #289 , #288 and #270)

I'll close this issue just to try and reduce the number of GitHub issues we're trying to manage!

**Comment by adamdewey** [comment]
Temperature spikes issue: https://github.com/msupply-foundation/msupply-cold-chain/issues/251
Skipped / duplicate logs issue: https://github.com/msupply-foundation/msupply-cold-chain/issues/318
