### ISSUE TITLE
Possibility to extract all data of sensors set up on one tablet at once. 

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/msupply-cold-chain#99]
Currently, you can only download data from sensor 1 by 1. Would be nice do extract all data of all sensors of one tablet.

**Comment by joshxg** [comment]
Not sure where this should go in the interface 🤔

**Comment by richardmoizeau** [comment]
Could go in the settings ? 

Consultant
The mSupply Foundation
Auckland, New Zealand
***@***.***
https://msupply.foundation

**Comment by mark-prins** [comment]
closing in favour of #285
